from sqlalchemy import (
    CheckConstraint,
    Column,
    Computed,
    ForeignKey,
    Index,
    String,
    Table,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin
from app.models.condition import Condition
from app.models.specialty import Specialty

# Plain association table (no extra columns), so it doesn't need a mapped class.
# The composite PK starts with provider_id; the separate condition_id index serves
# "which providers treat X".
provider_conditions = Table(
    "provider_conditions",
    Base.metadata,
    Column("provider_id", ForeignKey("providers.id", ondelete="CASCADE"), primary_key=True),
    Column(
        "condition_id",
        ForeignKey("conditions.id", ondelete="CASCADE"),
        primary_key=True,
        index=True,
    ),
)


class Provider(TimestampMixin, Base):
    """A clinician. Metrics that a data source doesn't publish are NULL, never zero:
    CMS publishes no complication or readmission rate per clinician, and not every
    clinician has a MIPS score or a graduation year. The CHECK constraints below all
    pass for NULL.
    """

    __tablename__ = "providers"
    __table_args__ = (
        CheckConstraint("credential IN ('MD', 'DO')", name="credential_valid"),
        CheckConstraint("data_source IN ('synthetic', 'cms')", name="data_source_valid"),
        CheckConstraint("npi ~ '^[0-9]{10}$'", name="npi_format"),
        # Every CMS row is identified by its NPI; synthetic providers must not have one.
        CheckConstraint("(data_source = 'cms') = (npi IS NOT NULL)", name="npi_matches_source"),
        CheckConstraint("quality_score BETWEEN 0 AND 100", name="quality_score_range"),
        CheckConstraint("complication_rate BETWEEN 0 AND 1", name="complication_rate_range"),
        CheckConstraint("readmission_rate BETWEEN 0 AND 1", name="readmission_rate_range"),
        CheckConstraint("years_experience BETWEEN 0 AND 70", name="years_experience_range"),
        CheckConstraint("cost_index > 0", name="cost_index_positive"),
        CheckConstraint("patient_volume >= 0", name="patient_volume_non_negative"),
        CheckConstraint("latitude BETWEEN -90 AND 90", name="latitude_range"),
        CheckConstraint("longitude BETWEEN -180 AND 180", name="longitude_range"),
        # Leading specialty_id also covers the FK and specialty-only filters.
        Index("ix_providers_specialty_id_state", "specialty_id", "state"),
        # Radius search prefilters on a lat/lon bounding box.
        Index("ix_providers_latitude_longitude", "latitude", "longitude"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    # National Provider Identifier; CMS rows only. UNIQUE allows many NULLs.
    npi: Mapped[str | None] = mapped_column(String(10), unique=True)
    data_source: Mapped[str] = mapped_column(String(10), server_default="synthetic")
    first_name: Mapped[str] = mapped_column(String(100))
    last_name: Mapped[str] = mapped_column(String(100))
    credential: Mapped[str] = mapped_column(String(2))
    specialty_id: Mapped[int] = mapped_column(ForeignKey("specialties.id"))
    subspecialty: Mapped[str | None] = mapped_column(String(100))

    city: Mapped[str] = mapped_column(String(100))
    state: Mapped[str] = mapped_column(String(2))
    zip_code: Mapped[str] = mapped_column(String(5))
    latitude: Mapped[float]
    longitude: Mapped[float]

    # NULL: not published (CMS: no or implausible graduation year). Scored as the
    # specialty median; see services/imputation.py.
    years_experience: Mapped[int | None]
    # 0-100. NULL: not published (CMS: no MIPS final score, or a final score of 0, which
    # means nothing scorable was submitted). Scored as the specialty median.
    quality_score: Mapped[float | None]
    # Generated by the database, so it can't disagree with quality_score: true when the
    # score is missing and every score of this provider uses an imputed value instead.
    quality_imputed: Mapped[bool] = mapped_column(Computed("quality_score IS NULL", persisted=True))
    # Lower is better. Synthetic: cost, 1.0 = regional average. CMS: Medicare spending per
    # patient, 1.0 = the NJ specialty median; NULL when not reported (suppressed, or too
    # few patients). Scored as the specialty median when NULL.
    cost_index: Mapped[float | None]
    # Annual patients (CMS: Medicare beneficiaries only).
    patient_volume: Mapped[int]
    complication_rate: Mapped[float | None]
    readmission_rate: Mapped[float | None]
    # NULL: unknown (CMS doesn't publish it). No default, so a row that leaves it out is
    # unknown rather than quietly "accepting".
    accepting_new_patients: Mapped[bool | None]

    specialty: Mapped[Specialty] = relationship()
    # passive_deletes: let ON DELETE CASCADE clean up provider_conditions rows.
    conditions: Mapped[list[Condition]] = relationship(
        secondary=provider_conditions, passive_deletes=True
    )
