"""create initial schema

Revision ID: 623b10afb234
Revises:
Create Date: 2026-09-25 04:24:32.014019

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "623b10afb234"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("name", "state", name=op.f("uq_cities_name_state")),
    )
    op.create_table(
        "conditions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conditions")),
        sa.UniqueConstraint("name", name=op.f("uq_conditions_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_conditions_slug")),
    )
    op.create_table(
        "specialties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specialties")),
        sa.UniqueConstraint("name", name=op.f("uq_specialties_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_specialties_slug")),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("credential", sa.String(length=2), nullable=False),
        sa.Column("specialty_id", sa.Integer(), nullable=False),
        sa.Column("subspecialty", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip_code", sa.String(length=5), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("years_experience", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Double(), nullable=False),
        sa.Column("cost_index", sa.Double(), nullable=False),
        sa.Column("patient_volume", sa.Integer(), nullable=False),
        sa.Column("complication_rate", sa.Double(), nullable=False),
        sa.Column("readmission_rate", sa.Double(), nullable=False),
        sa.Column(
            "accepting_new_patients", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credential IN ('MD', 'DO')", name=op.f("ck_providers_credential_valid")
        ),
        sa.CheckConstraint(
            "complication_rate BETWEEN 0 AND 1", name=op.f("ck_providers_complication_rate_range")
        ),
        sa.CheckConstraint("cost_index > 0", name=op.f("ck_providers_cost_index_positive")),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_providers_latitude_range")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_providers_longitude_range")
        ),
        sa.CheckConstraint(
            "patient_volume >= 0", name=op.f("ck_providers_patient_volume_non_negative")
        ),
        sa.CheckConstraint(
            "quality_score BETWEEN 0 AND 100", name=op.f("ck_providers_quality_score_range")
        ),
        sa.CheckConstraint(
            "readmission_rate BETWEEN 0 AND 1", name=op.f("ck_providers_readmission_rate_range")
        ),
        sa.CheckConstraint(
            "years_experience BETWEEN 0 AND 70", name=op.f("ck_providers_years_experience_range")
        ),
        sa.ForeignKeyConstraint(
            ["specialty_id"], ["specialties.id"], name=op.f("fk_providers_specialty_id_specialties")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
    )
    op.create_index(
        "ix_providers_latitude_longitude", "providers", ["latitude", "longitude"], unique=False
    )
    op.create_index(
        "ix_providers_specialty_id_state", "providers", ["specialty_id", "state"], unique=False
    )
    op.create_table(
        "search_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("parser_used", sa.String(length=20), nullable=True),
        sa.Column("specialty_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Double(), nullable=False),
        sa.CheckConstraint("source IN ('nl', 'manual')", name=op.f("ck_search_logs_source_valid")),
        sa.ForeignKeyConstraint(
            ["specialty_id"],
            ["specialties.id"],
            name=op.f("fk_search_logs_specialty_id_specialties"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_logs")),
    )
    op.create_index(op.f("ix_search_logs_created_at"), "search_logs", ["created_at"], unique=False)
    op.create_table(
        "provider_conditions",
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["conditions.id"],
            name=op.f("fk_provider_conditions_condition_id_conditions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_provider_conditions_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("provider_id", "condition_id", name=op.f("pk_provider_conditions")),
    )
    op.create_index(
        op.f("ix_provider_conditions_condition_id"),
        "provider_conditions",
        ["condition_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provider_conditions_condition_id"), table_name="provider_conditions")
    op.drop_table("provider_conditions")
    op.drop_index(op.f("ix_search_logs_created_at"), table_name="search_logs")
    op.drop_table("search_logs")
    op.drop_index("ix_providers_specialty_id_state", table_name="providers")
    op.drop_index("ix_providers_latitude_longitude", table_name="providers")
    op.drop_table("providers")
    op.drop_table("specialties")
    op.drop_table("conditions")
    op.drop_table("cities")
    # ### end Alembic commands ###
