from typing import Literal, Self

from pydantic import BaseModel

from app.models import Provider
from app.schemas.reference import ConditionRef, SpecialtyRef
from app.schemas.score import ProviderScore

# reported: the value is in the response. imputed: not published, and scores use the
# specialty median instead (the value itself stays null). not_reported: not published,
# and not part of any score.
MetricStatus = Literal["reported", "imputed", "not_reported"]


class MetricFlags(BaseModel):
    """What each metric that can be missing means for this provider. Patient volume is
    always present."""

    quality_score: MetricStatus
    years_experience: MetricStatus
    cost_index: MetricStatus
    complication_rate: MetricStatus
    readmission_rate: MetricStatus

    @classmethod
    def from_model(cls, provider: Provider) -> Self:
        return cls(
            # quality_imputed is generated by the database from quality_score IS NULL.
            quality_score="imputed" if provider.quality_imputed else "reported",
            years_experience="imputed" if provider.years_experience is None else "reported",
            cost_index="imputed" if provider.cost_index is None else "reported",
            complication_rate=_reported_or_not(provider.complication_rate),
            readmission_rate=_reported_or_not(provider.readmission_rate),
        )


class ProviderSummary(BaseModel):
    id: int
    # National Provider Identifier; CMS data only.
    npi: str | None
    data_source: Literal["synthetic", "cms"]
    display_name: str
    specialty: SpecialtyRef
    subspecialty: str | None
    city: str
    state: str
    # Null when not published; see metric_flags.
    years_experience: int | None
    quality_score: float | None
    # Lower is better. Synthetic: cost, 1.0 = regional average. CMS: Medicare spending per
    # patient, 1.0 = the NJ specialty median; null when not reported (see metric_flags).
    cost_index: float | None
    # Null when unknown (CMS doesn't publish it).
    accepting_new_patients: bool | None
    metric_flags: MetricFlags

    @classmethod
    def from_model(cls, provider: Provider) -> Self:
        """Build from a Provider whose specialty is already loaded."""
        return cls(**_summary_fields(provider))


class ProviderDetail(ProviderSummary):
    zip_code: str
    latitude: float
    longitude: float
    # Annual patients (CMS: Medicare beneficiaries only).
    patient_volume: int
    complication_rate: float | None
    readmission_rate: float | None
    conditions: list[ConditionRef]

    @classmethod
    def from_model(cls, provider: Provider) -> Self:
        """Build from a Provider whose specialty and conditions are already loaded."""
        return cls(
            **_summary_fields(provider),
            zip_code=provider.zip_code,
            latitude=provider.latitude,
            longitude=provider.longitude,
            patient_volume=provider.patient_volume,
            complication_rate=provider.complication_rate,
            readmission_rate=provider.readmission_rate,
            conditions=[
                ConditionRef.model_validate(condition)
                for condition in sorted(provider.conditions, key=lambda c: c.name)
            ],
        )


class ScoredProviderDetail(ProviderDetail):
    """A provider detail scored the same way a search would score it."""

    # Rounded to 0.1 mile; null when no location was given.
    distance_miles: float | None
    score: ProviderScore
    explanation: str


def _reported_or_not(value: float | None) -> MetricStatus:
    return "not_reported" if value is None else "reported"


def _summary_fields(provider: Provider) -> dict[str, object]:
    return {
        "id": provider.id,
        "npi": provider.npi,
        "data_source": provider.data_source,
        "display_name": f"Dr. {provider.first_name} {provider.last_name}, {provider.credential}",
        "specialty": SpecialtyRef.model_validate(provider.specialty),
        "subspecialty": provider.subspecialty,
        "city": provider.city,
        "state": provider.state,
        "years_experience": provider.years_experience,
        "quality_score": provider.quality_score,
        "cost_index": provider.cost_index,
        "accepting_new_patients": provider.accepting_new_patients,
        "metric_flags": MetricFlags.from_model(provider),
    }
